@startebnf
skinparam defaultfontname "Open Sans"
commit = ("doc" | "feat" | "fix" | "style" | "perf" | "code" | "structure" | "test" | "git" | "build"), ["(", component,")"], ["[", issue, "]"], change;
@endebnf