@startebnf
skinparam defaultfontname "Open Sans"
child-issue-title = ("PA" | "CA"), ":", title;
child-issue-content = ("Pending action" | "Conditional action"), "[", issue, "]:", description;
child-issue-resolution = "Resolve", ("pending action" | "conditional action"), "...";
@endebnf