@startebnf
skinparam defaultfontname "Open Sans"
child-issue-title = ("FA" | "PC"), ":", title;
child-issue-content = ("Future action" | "Pending change"), "from", "(", issue, "):", description;
child-issue-resolution = "Resolve", ("future action" | "pending change"), "...";
@endebnf