@startebnf
skinparam defaultfontname "Open Sans"
commit = prefix, ["(", component,")"], ["[", issue, "]"], change;
in-commit = "In commit", "[", commit, "]:", ("address problem" | "apply solution" | ?other reasons?);
@endebnf