@startebnf
skinparam defaultfontname "Open Sans"
commit = prefix, ["(", component,")"], ["[", issue, "]"], change;
in-commit = "In commit", "[", commit, "]:", ("address proposed problem" | "apply proposed solution" | ?other reasons?);
@endebnf